name: Build and Release

# Run on every commit tag which begins with "v" (e.g., v0.1.4)
on:
  push:
    tags:
      - "v*"

# Automatically create a Github Release, with release details specified (the relevant commits)
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        prerelease: false

  deploy:
    name: Deploy release build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: cp /app/.env.production .
    - run: docker compose --env-file .env.production up -d --no-deps --build backend